language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

cache:
  directories:
    - vendor

matrix:
  allow_failures:
    - php: nightly

sudo: false

before_script:
  - composer install

script:
  - vendor/bin/phpunit
  - vendor/bin/atoum --test-ext -ulr
